<?php session_start(); ?>
<html>
	<head>
		<title>Camagru login</title>
		<link rel="stylesheet" href="./css/login.css">
		<link href='https://fonts.googleapis.com/css?family=Bigelow Rules' rel='stylesheet'>
		<link href='https://fonts.googleapis.com/css?family=Black And White Picture' rel='stylesheet'>
	</head>
	<body>
		<form id="login-form" action="./php/login.php" method="post" autocomplete="off">
			<div class="input-title">Username
				<?php
				if (isset($_GET["error"]) && $_GET["error"] == 1)
				{
					echo " (incorrect)";
				}
				?>
			</div>
			<input autocomple class="input-field" type="text" name="account"
				<?php
					if (isset($_SESSION["account"]))
					{
						echo 'value="'.$_SESSION["account"].'"';
					}
				?>
			required>
			<div class="input-title">Password
				<?php
				if (isset($_GET["error"]) && $_GET["error"] == 2)
				{
					echo " (incorrect)";
				}
				?>
			</div>
			<input class="input-field" type="password" name="pw" required <?php
					if (isset($_SESSION["account"]))
					{
						echo 'autofocus';
					}
				?>
			><br>
			<input type="submit" value="Submit" required>
		</form>
	</body>
</html>
